name: ci

on: [push, pull_request]

jobs:
  build-leaf-android:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: install rust toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: install deps
        run: |
          cargo install cbindgen
          apt update && apt install -y make llvm-dev libclang-dev clang pkg-config unzip curl default-jdk build-essential
      - name: build
        run: |
          export ANDROID_HOME=/tmp/Android/sdk
          export NDK_HOME=/tmp/Android/sdk/ndk/25.2.9519653
          export PATH=$ANDROID_HOME/cmdline-tools/bin:$PATH
          export PATH=~/.cargo/bin:$PATH
          WD=`pwd`
          # install Android SDK and NDK
          cd /tmp/
          curl -OL https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
          unzip commandlinetools-linux-6858069_latest.zip
          mkdir -p $ANDROID_HOME
          mv cmdline-tools $ANDROID_HOME
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
          sdkmanager --sdk_root=$ANDROID_HOME "ndk;25.2.9519653" "platforms;android-21"
          cd $WD
          # add targets
          rustup target add aarch64-linux-android x86_64-linux-android i686-linux-android armv7-linux-androideabi
          
          # build
          ./app/src/main/rust/leaf-android/build.sh release

      - name: copy artifacts
        run: |
          cp app/src/main/rust/leaf-android/target/x86_64-linux-android/release/libleaf.so libleaf-x86_64-linux-android.so
          cp app/src/main/rust/leaf-android/target/aarch64-linux-android/release/libleaf.so libleaf-aarch64-linux-android.so
          cp app/src/main/rust/leaf-android/target/armv7-linux-androideabi/release/libleaf.so libleaf-armv7-linux-android.so
          cp app/src/main/rust/leaf-android/target/i686-linux-android/release/libleaf.so libleaf-i686-linux-android.so

      - name: upload assets
        uses: actions/upload-artifact@v2
        with:
          name: libleaf-x86_64-linux-android.so
          path: libleaf-x86_64-linux-android.so

      - name: upload assets
        uses: actions/upload-artifact@v2
        with:
          name: libleaf-aarch64-linux-android.so
          path: libleaf-aarch64-linux-android.so

      - name: upload assets
        uses: actions/upload-artifact@v2
        with:
          name: libleaf-armv7-linux-android.so
          path: libleaf-armv7-linux-android.so
          

      - name: upload assets
        uses: actions/upload-artifact@v2
        with:
          name: libleaf-i686-linux-android.so
          path: libleaf-i686-linux-android.so
          
